Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    config.vm.hostname = "multipass-vagrant-test-01"
    config.vm.synced_folder "./sync", "/vagrant", type: "rsync"
  
    # Provision
    # config.vm.provision "shell", inline "echo 'sudo su -' >> .bashrc"
    config.vm.provision "shell", inline: "apt update"
    config.vm.provision "shell", inline: "apt install -y conntrack bridge-utils net-tools resolvconf jq tree"
  
    config.vm.provider "virtualbox" do |vb, override|
      vb.cpus = 2
      vb.memory = 2048
    end
  end